### ISSUE TITLE
Issue 1 : Issue with Add new class room option

### ISSUE THREAD

**Issue by 26pooja** [ufrshubham/SDBMS#1]
It allows to add  new class room number with the same existing class room number.

**Comment by ufrshubham** [comment]
Most probably this issue can be fixed if we add some kind of checking while class creation. But this kind of validation might require us to traverse all the elements of globalDataManager just to find out the class room numbers that have already been used.

One other way would be to change globalDataManager from deque to set. This will ensure that the validation is performed automatically whenever we insert new objects into the set. But for this the < operator of ClassRoomData will have to be overloaded such that it checks the class room number of current and other object.
