### ISSUE TITLE
Program terminates if user tries to delete multiple student data at a time

### ISSUE THREAD

**Issue by 26pooja** [ufrshubham/SDBMS#10]
Select option 3 "Edit existing class room" and after that select option to "Delete existing student data" .
It asks us to "Enter roll numbers of students to be deleted:" .So if we try to enter multiple roll numbers the program terminates

**Comment by ufrshubham** [comment]
Surprisingly, if we try to delete multiple student in sequence, it does not crash.

**Comment by ufrshubham** [comment]
I thought it was sequence that mattered, but I was wrong. This seems to be a bug only in debug build. It passes in release build. Following are the steps that I preformed.

Steps:
1. Add a new class with 5 students.
2. Delete 2nd and 4th student from this class.

**Comment by ufrshubham** [comment]
Fixed in bug fix sprint 3
