### ISSUE TITLE
Priority of roll number for new student

### ISSUE THREAD

**Issue by ufrshubham** [ufrshubham/SDBMS#8]
If a class has some unused roll numbers (i.e. because of deletion of some students), then in such case if a new student is being added to the class, we should assign the unused roll to new student.

**Comment by 26pooja** [comment]
If we have added 5 students data in one class . And we have deleted 3rd and 5th student data . 
So while adding new student data it should assign roll no 3 to that student . Right . Is that what you are saying ?

**Comment by 26pooja** [comment]
Issue is fixed
